controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation

admin:
    path: /admin
    controller: App\Controller\DashboardController::index
    methods: GET



